feelings/feelings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'), name='users'),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
]

feelings/users/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'users'
urlpatterns = [
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('', include('django.contrib.auth.urls')),
]

feelings/thoughts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
CONDITIONS = (
    (5, 'Joy'),
    (10, 'Passionate'),
    (15, 'Happy'),
    (20, 'Optimistic'),
    (25, 'Content'),
    (30, 'Bored'),
    (31, 'Tired'),
    (33, 'Hungry'),
    (35,'Pessimistic'),
    (40, 'Frustrated'),
    (45,'Overwhelmed'),
    (50,'Dissapointed'),
    (55, 'Worried'),
    (60, 'Angry'),
    (65, 'Jealous'),
    (70, 'Insecure'),
    (75, 'Guilty'),
    (80, 'Fear'),
    (85, 'Grief'),
    (90, 'Despair'),
)


class Thought(models.Model):
    user = models.ForeignKey(User, related_name='thoughts', on_delete=models.CASCADE)
    recorded_at = models.DateField(default=timezone.now, editable=False)
    condition = models.IntegerField(choices=CONDITIONS)
    notes = models.TextField(blank=True, default='')

    def __str__(self):
        return '{}: {}'.format(self.recorded_at.strftime('%Y-%m-%d %H:%M'), self.get_condition_display())

feelings/users/models.py
from django.db import models

# Create your models here.

feelings/thoughts/forms.py
from django import forms

from . import models


class ThoughtForm(forms.ModelForm):
    class Meta:
        model = models.Thought
        fields = ['condition', 'notes']

feelings/users/forms.py
from django import forms


class LogoutForm(forms.Form):
    pass

feelings/users/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import FormView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from .forms import LogoutForm


def dashboard(request):
    return render(request, 'users/dashboard.html')


class LogoutView(LoginRequiredMixin, FormView):
    form_class = LogoutForm
    template_name = 'registration/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))


class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'

    def get_success_url(self):
        return reverse_lazy('users:login')

feelings/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a
                jumbotron and three supporting pieces of content. Use it as a starting point to create something more
                unique.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula
                    porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh,
                    ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>

        <hr>

    </div> <!-- /container -->

</main>
<div class="container"><h1>Welcome to Feelings</h1>
</div>
{% endblock %}

feelings/templates/layout.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/feelings.css' %}">

    <title>{% block title %}Feelings{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Feelings</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-right" id="navbarsExampleDefault">
        {% if not user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:login' %}">Login <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:signup' %}">Sign Up<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Record <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">History <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% endif %}
        <!--<form class="form-inline my-2 my-lg-0">-->
        <!--<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
        <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
        <!--</form>-->
    </div>
</nav>
<div id="content">
    {% block content %}{% endblock %}
</div>
<div class="container">
    <footer class="container">
        <hr>
        <p>&copy; Company 2017-2018</p>
    </footer>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

feelings/thoughts/templates/thoughts/_form.html
{% load bootstrap3 %}

<form action="#" method="POST">
    <h2>How are you feeling now?</h2>
    <div class="row">
        <div class="col-md-4">{% bootstrap_field form.condition %}</div>
        <div class="col-md-8">{% bootstrap_field form.notes %}</div>
    </div>
    {% csrf_token %}
    <input type="submit" value="Record" class="btn"/>
</form>

feelings/users/templates/users/dashboard.html
{% extends 'layout.html' %}
{% load thought_tags %}

{% block title %}Dashboard | {{ block.super }}{% endblock %}
{% block content %}
<div class="container pt">
    <div class="row">
        {% thought_form %}
    </div>
    <div class="row">
        <h2>Dashboard</h2>
    </div>
</div>
{% endblock %}